spring.application.name=websiteElectronics

spring.datasource.url=jdbc:mysql://localhost:3306/electronics_websites_db
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quyen12079@gmail.com
spring.mail.password=vbcnfwnddeoljubg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Invoice configuration
invoice.folder.path=D:/websiteElectronics/invoices

# Order configuration
report.folder.path=D:/websiteElectronics/reports

# ============================================
# GOOGLE OAUTH2
# ============================================
spring.security.oauth2.client.registration.google.client-id=5340255641-jrr5augmt24tjn7losin8tkb8ltimavi.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# ============================================
# JWT Configuration
# ============================================
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation12345678901234567890
jwt.expiration=86400000

# ==========================================
# ChatBot
# ==========================================
gemini.api.key=AIzaSyDzPEW3htiimNmETy4FNWl6tbk8zfhhQVk
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# ============================================
# OAuth2 Authorization Server
# ============================================
# Issuer URL - Authorization Server
spring.security.oauth2.authorizationserver.issuer=http://localhost:8080

# Logging cho OAuth2
logging.level.org.springframework.security.oauth2=DEBUG